@echo off
setlocal enabledelayedexpansion

rem -----------------------------------------------------------------
rem 1) 让当前目录下的 .ioc 与上一级目录的 .code-workspace 同名
rem -----------------------------------------------------------------

set "CUBEMX_DIR=%~dp0"

rem 计算工程根目录（上一级目录）
for %%I in ("%CUBEMX_DIR%..") do set "ROOT_DIR=%%~fI\"

set "WORKSPACE_NAME="
set "IOC_NAME_FILE="

rem 在工程根目录查找 .code-workspace，取第一个文件名（不含扩展名）
for %%F in ("%ROOT_DIR%*.code-workspace") do if not defined WORKSPACE_NAME set "WORKSPACE_NAME=%%~nF"

if defined WORKSPACE_NAME (
	rem 在当前目录查找 .ioc，取第一个文件名
	for %%J in ("%CUBEMX_DIR%*.ioc") do if not defined IOC_NAME_FILE set "IOC_NAME_FILE=%%~nxJ"

	if defined IOC_NAME_FILE (
		rem 如果当前 .ioc 名称与工作区名不同，则改名
		if /I not "!IOC_NAME_FILE!"=="!WORKSPACE_NAME!.ioc" (
			pushd "%CUBEMX_DIR%"
			ren "!IOC_NAME_FILE!" "!WORKSPACE_NAME!.ioc" 2>nul
			popd
		)
	)
)

rem -----------------------------------------------------------------
rem 2) 生成聚合头文件：自动包含 CubeMX/Core/Inc 下的所有 .h
rem    生成文件：CubeMX/Core/Inc/cubemx.h
rem -----------------------------------------------------------------

set "CORE_INC=%ROOT_DIR%CubeMX\Core\Inc\"
set "AGG_HEADER=%CORE_INC%cubemx.h"

rem 写入头文件保护和说明
> "%AGG_HEADER%" echo /**
>> "%AGG_HEADER%" echo * @file    cubemx.h
>> "%AGG_HEADER%" echo * @author  Pickingchip
>> "%AGG_HEADER%" echo * @brief   this file is used to include the CubeMX generated peripheral header files.
>> "%AGG_HEADER%" echo * @note    Auto-generated by cleanup.bat after CubeMX code generation.
>> "%AGG_HEADER%" echo * @version 1.0
>> "%AGG_HEADER%" echo * @date    2026-03-16
>> "%AGG_HEADER%" echo */

>> "%AGG_HEADER%" echo #ifndef __CUBEMX_H
>> "%AGG_HEADER%" echo #define __CUBEMX_H
>> "%AGG_HEADER%" echo.
>> "%AGG_HEADER%" echo #ifdef __cplusplus
>> "%AGG_HEADER%" echo extern "C" {
>> "%AGG_HEADER%" echo #endif
>> "%AGG_HEADER%" echo.

rem 遍历 Core/Inc 目录下的所有 .h，逐个生成 #include 行
for %%H in ("%CORE_INC%*.h") do (
	if /I not "%%~nxH"=="cubemx.h" (
		>> "%AGG_HEADER%" echo #include "%%~nxH"
	)
)

>> "%AGG_HEADER%" echo.
>> "%AGG_HEADER%" echo #ifdef __cplusplus
>> "%AGG_HEADER%" echo }
>> "%AGG_HEADER%" echo #endif
>> "%AGG_HEADER%" echo.
>> "%AGG_HEADER%" echo #endif /* __CUBEMX_H */

rem -----------------------------------------------------------------
rem 3) 删除 MDK-ARM 目录：先简单延时，给 CubeMX 一点时间释放句柄
rem -----------------------------------------------------------------

rem 适当加长延时，避免偶尔句柄释放较慢
rem timeout /t 8 /nobreak >nul

rem 脚本放在工程根目录（和 .ioc 同一层）
set "PROJECT_DIR=%~dp0"
set "TARGET=%PROJECT_DIR%MDK-ARM"

if not exist "%TARGET%" goto :done

echo Removing "%TARGET%" ...

rem 重试次数
set "retries=10"

:retry
rem 1. 去掉所有文件/子目录的只读/隐藏/系统属性
attrib -R -S -H "%TARGET%\*.*" /S /D 2>nul

rem 2. 强制删除目录中的所有文件
del /F /Q "%TARGET%\*.*" 2>nul

rem 3. 递归删除所有子目录
for /d %%D in ("%TARGET%\*") do rd /S /Q "%%D" 2>nul

rem 4. 尝试删除 MDK-ARM 目录本身
rd /S /Q "%TARGET%" 2>nul

rem 5. 如果已经删掉就结束；否则重试几次
if not exist "%TARGET%" goto :done

set /a retries-=1
if !retries! LEQ 0 goto :done

rem timeout /t 1 >nul
goto :retry

:done
endlocal
exit /b 0