@echo off
setlocal enabledelayedexpansion

rem -----------------------------------------------------------------
rem 1) 让当前目录下的 .ioc 与上一级目录的 .code-workspace 同名
rem -----------------------------------------------------------------

set "CUBEMX_DIR=%~dp0"

rem 计算工程根目录（上一级目录）
for %%I in ("%CUBEMX_DIR%..") do set "ROOT_DIR=%%~fI\"

set "WORKSPACE_NAME="
set "IOC_NAME_FILE="

rem 在工程根目录查找 .code-workspace，取第一个文件名（不含扩展名）
for %%F in ("%ROOT_DIR%*.code-workspace") do if not defined WORKSPACE_NAME set "WORKSPACE_NAME=%%~nF"

if defined WORKSPACE_NAME (
	rem 在当前目录查找 .ioc，取第一个文件名
	for %%J in ("%CUBEMX_DIR%*.ioc") do if not defined IOC_NAME_FILE set "IOC_NAME_FILE=%%~nxJ"

	if defined IOC_NAME_FILE (
		rem 如果当前 .ioc 名称与工作区名不同，则改名
		if /I not "!IOC_NAME_FILE!"=="!WORKSPACE_NAME!.ioc" (
			pushd "%CUBEMX_DIR%"
			ren "!IOC_NAME_FILE!" "!WORKSPACE_NAME!.ioc" 2>nul
			popd
		)
	)

	rem 令 .ioc 文件内部的 ProjectManager.ProjectFileName / ProjectManager.ProjectName 与文件名保持一致
	set "IOC_FILE=%CUBEMX_DIR%!WORKSPACE_NAME!.ioc"
	if exist "!IOC_FILE!" (
		powershell -Command "$file = '!IOC_FILE!'; $name = '!WORKSPACE_NAME!'; $pf = $name + '.ioc'; $c = Get-Content -Path $file; $c | ForEach-Object { if ($_ -like 'ProjectManager.ProjectFileName=*') { 'ProjectManager.ProjectFileName=' + $pf } elseif ($_ -like 'ProjectManager.ProjectName=*') { 'ProjectManager.ProjectName=' + $name } else { $_ } } | Set-Content -Path $file"
	)
)

rem -----------------------------------------------------------------
rem 2) 生成聚合头文件：自动包含 CubeMX/Core/Inc 下的所有 .h
rem    生成文件：CubeMX/Core/Inc/cubemx.h
rem -----------------------------------------------------------------

set "CORE_INC=%ROOT_DIR%CubeMX\Core\Inc\"
set "AGG_HEADER=%CORE_INC%cubemx.h"

rem 写入头文件保护和说明
> "%AGG_HEADER%" echo /**
>> "%AGG_HEADER%" echo * @file    cubemx.h
>> "%AGG_HEADER%" echo * @author  Pickingchip
>> "%AGG_HEADER%" echo * @brief   this file is used to include the CubeMX generated peripheral header files.
>> "%AGG_HEADER%" echo * @note    Auto-generated by cleanup.bat after CubeMX code generation.
>> "%AGG_HEADER%" echo * @version 1.0
>> "%AGG_HEADER%" echo * @date    2026-03-16
>> "%AGG_HEADER%" echo */

>> "%AGG_HEADER%" echo #ifndef __CUBEMX_H
>> "%AGG_HEADER%" echo #define __CUBEMX_H
>> "%AGG_HEADER%" echo.
>> "%AGG_HEADER%" echo #ifdef __cplusplus
>> "%AGG_HEADER%" echo extern "C" {
>> "%AGG_HEADER%" echo #endif
>> "%AGG_HEADER%" echo.

rem 遍历 Core/Inc 目录下的所有 .h，逐个生成 #include 行
for %%H in ("%CORE_INC%*.h") do (
	if /I not "%%~nxH"=="cubemx.h" (
		>> "%AGG_HEADER%" echo #include "%%~nxH"
	)
)

>> "%AGG_HEADER%" echo.
>> "%AGG_HEADER%" echo #ifdef __cplusplus
>> "%AGG_HEADER%" echo }
>> "%AGG_HEADER%" echo #endif
>> "%AGG_HEADER%" echo.
>> "%AGG_HEADER%" echo #endif /* __CUBEMX_H */

rem -----------------------------------------------------------------
rem 3) 根据 .ioc 的工具链类型执行清理
rem    - 若为 MDK-ARM：保持原逻辑，仅删除 MDK-ARM 目录
rem    - 若为 Makefile：删除同级 Makefile 和 .s，移动 .ld 并更新 eide.yml
rem -----------------------------------------------------------------

rem 确定 .ioc 文件路径（优先使用与工作区同名的 .ioc）
set "IOC_FILE="
if defined WORKSPACE_NAME if exist "%CUBEMX_DIR%%WORKSPACE_NAME%.ioc" set "IOC_FILE=%CUBEMX_DIR%%WORKSPACE_NAME%.ioc"
if not defined IOC_FILE (
	for %%J in ("%CUBEMX_DIR%*.ioc") do if not defined IOC_FILE set "IOC_FILE=%%~fJ"
)

if not defined IOC_FILE goto :done

rem 解析 ProjectManager.TargetToolchain
set "TARGET_TOOLCHAIN="
for /f "usebackq tokens=1* delims==" %%A in ("%IOC_FILE%") do (
	if /I "%%A"=="ProjectManager.TargetToolchain" (
		set "TARGET_TOOLCHAIN=%%B"
	)
)

rem 根据工具链分支执行：只要不是 Makefile 就按 MDK-ARM 处理
if /I "%TARGET_TOOLCHAIN%"=="Makefile" goto :cleanup_makefile
goto :cleanup_mdk

:cleanup_mdk
rem -----------------------------------------------------------------
rem MDK-ARM 工程：
rem  - 删除 MDK-ARM 目录
rem  - 将 .eide\eide.yml 中 startup 路径中的 gcc 改为 arm
rem -----------------------------------------------------------------

rem 脚本放在 CubeMX 目录
set "PROJECT_DIR=%~dp0"
set "TARGET=%PROJECT_DIR%MDK-ARM"

rem 更新 .eide\eide.yml 中 startup 路径：Source/gcc -> Source/arm，并将 toolchain 设为 AC6
set "EIDE_FILE=%ROOT_DIR%.eide\eide.yml"
if exist "%EIDE_FILE%" (
	powershell -Command "$file = '%EIDE_FILE%'; $c = Get-Content -Path $file; $c = $c -replace 'Source/gcc/','Source/arm/'; $c = $c -replace '^\s*toolchain:.*$','    toolchain: AC6'; Set-Content -Path $file -Value $c"
)

if not exist "%TARGET%" goto :done

echo Removing "%TARGET%" ...

attrib -R -S -H "%PROJECT_DIR%Makefile" 2>nul
del /F /Q "%PROJECT_DIR%Makefile" 2>nul

rem 重试次数
set "retries=10"

:retry_mdk
rem 1. 去掉所有文件/子目录的只读/隐藏/系统属性
attrib -R -S -H "%TARGET%\*.*" /S /D 2>nul

rem 2. 强制删除目录中的所有文件
del /F /Q "%TARGET%\*.*" 2>nul

rem 3. 递归删除所有子目录
for /d %%D in ("%TARGET%\*") do rd /S /Q "%%D" 2>nul

rem 4. 尝试删除 MDK-ARM 目录本身
rd /S /Q "%TARGET%" 2>nul

rem 5. 如果已经删掉就结束；否则重试几次
if not exist "%TARGET%" goto :done

set /a retries-=1
if !retries! LEQ 0 goto :done

goto :retry_mdk

:cleanup_makefile
rem -----------------------------------------------------------------
rem Makefile 工程：
rem  - 删除脚本同级目录下的 Makefile 和所有 .s 文件
rem  - 将 .ld 文件移动到 Drivers\CMSIS\Device\ST\STM32F4xx\Source\ld
rem  - 更新 .eide\eide.yml 中的 .ld 路径
rem  - 将 .eide\eide.yml 中 startup 路径中的 arm 改为 gcc
rem -----------------------------------------------------------------

set "PROJECT_DIR=%~dp0"

rem 删除 Makefile（增加多次重试，避免文件被短暂占用导致删除失败）
set "mf_retries=10"

timeout /t 2 >nul

:retry_makefile
if not exist "%PROJECT_DIR%Makefile" goto :after_makefile

rem 去掉只读/隐藏/系统属性
attrib -R -S -H "%PROJECT_DIR%Makefile" 2>nul

del /F /Q "%PROJECT_DIR%Makefile" 2>nul
if not exist "%PROJECT_DIR%Makefile" goto :after_makefile

set /a mf_retries-=1
if !mf_retries! LEQ 0 goto :after_makefile

timeout /t 1 >nul
goto :retry_makefile

:after_makefile

rem 删除同级目录下所有 .s 文件
for %%S in ("%PROJECT_DIR%*.s") do (
	if exist "%%~fS" del /F /Q "%%~fS" 2>nul
)

rem 处理 .ld 文件：移动到 Drivers\CMSIS\Device\ST\STM32F4xx\Source\ld 目录
set "LD_SOURCE_DIR=%PROJECT_DIR%"
set "LD_TARGET_DIR=%ROOT_DIR%CubeMX\Drivers\CMSIS\Device\ST\STM32F4xx\Source\ld\"
set "LD_FILE="

for %%L in ("%LD_SOURCE_DIR%*.ld") do if not defined LD_FILE set "LD_FILE=%%~nxL"

if not defined LD_FILE goto :done

if not exist "%LD_TARGET_DIR%" mkdir "%LD_TARGET_DIR%"

move /Y "%LD_SOURCE_DIR%%LD_FILE%" "%LD_TARGET_DIR%" >nul

rem 更新 .eide\eide.yml 中 GCC 工具链的 scatterFilePath 以及 startup 路径中的 gcc/arm
set "EIDE_FILE=%ROOT_DIR%.eide\eide.yml"
if exist "%EIDE_FILE%" (
		rem 使用刚刚移动的 ld 文件名，生成完整相对路径
		rem 只在 GCC 段内覆盖 scatterFilePath 行，并将 toolchain 设为 GCC，不影响 AC6 段
		powershell -Command "$file = '%EIDE_FILE%'; $ldPath = '.\CubeMX\Drivers\CMSIS\Device\ST\STM32F4xx\Source\ld\%LD_FILE%'; $c = Get-Content -Path $file; $inGcc = $false; for ($i = 0; $i -lt $c.Count; $i++) { if ($c[$i] -match '^\s*GCC:\s*$') { $inGcc = $true; continue }; if ($inGcc -and $c[$i] -match '^\s*scatterFilePath:') { $c[$i] = '        scatterFilePath: ' + $ldPath; $inGcc = $false } }; $c = $c -replace '^\s*toolchain:.*$','    toolchain: GCC'; $c = $c -replace 'Source/arm/','Source/gcc/'; Set-Content -Path $file -Value $c"
)

:done
endlocal
exit /b 0