#!/usr/bin/env python3
"""
STM32工程模板清理脚本，CubeMX 代码生成后自动调用，兼容 Windows 和 Linux 环境。

实现以下功能：
1) 保持 .ioc 文件名称与工程名称同步。
2) 重新生成 CubeMX/Core/Inc/cubemx.h 作为聚合包含头文件。
3) 运行特定工具链的清理操作和 .eide/eide.yml 更新。

"""

from __future__ import annotations

import re
import shutil
import stat
import time
from pathlib import Path
from typing import Iterable, Optional

RETRY_COUNT = 10
RETRY_DELAY_SECONDS = 0.2
HEADER_DATE = "2026-03-16"


def read_text(path: Path) -> str:
    """读取文本文件内容（UTF-8）。"""
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    """以统一换行符写入文本文件（UTF-8）。"""
    path.write_text(content, encoding="utf-8", newline="\n")


def replace_line_values(lines: Iterable[str], mapping: dict[str, str]) -> list[str]:
    """按 key=value 形式替换指定键对应的整行值。"""
    out: list[str] = []
    for line in lines:
        replaced = False
        for key, value in mapping.items():
            prefix = f"{key}="
            if line.startswith(prefix):
                out.append(f"{prefix}{value}")
                replaced = True
                break
        if not replaced:
            out.append(line)
    return out


def remove_file(path: Path, retries: int = RETRY_COUNT) -> bool:
    """带重试删除文件，返回是否删除成功。"""
    for _ in range(retries):
        if not path.exists():
            return True
        try:
            path.chmod(stat.S_IWRITE | stat.S_IREAD)
        except OSError:
            pass
        try:
            path.unlink()
        except OSError:
            time.sleep(RETRY_DELAY_SECONDS)
    return not path.exists()


def _on_rm_error(func, path_str, _exc_info):
    """rmtree 删除失败时回调：先尝试去只读，再重试原操作。"""
    path = Path(path_str)
    try:
        path.chmod(stat.S_IWRITE | stat.S_IREAD)
    except OSError:
        pass
    func(path_str)


def remove_dir(path: Path, retries: int = RETRY_COUNT) -> bool:
    """带重试递归删除目录，返回是否删除成功。"""
    for _ in range(retries):
        if not path.exists():
            return True
        try:
            shutil.rmtree(path, onerror=_on_rm_error)
        except OSError:
            time.sleep(RETRY_DELAY_SECONDS)
    return not path.exists()


def find_first_by_suffix(directory: Path, suffix: str) -> Optional[Path]:
    """在目录中按名称排序，返回第一个指定后缀文件。"""
    candidates = sorted(p for p in directory.glob(f"*{suffix}") if p.is_file())
    return candidates[0] if candidates else None


def update_ioc_file_name(cubemx_dir: Path, root_dir: Path) -> tuple[Optional[str], Optional[Path]]:
    """同步 .ioc 文件名与工作区名，并更新 .ioc 内项目名称字段。"""
    workspace = find_first_by_suffix(root_dir, ".code-workspace")
    if workspace is None:
        return None, None

    workspace_name = workspace.stem
    ioc_file = find_first_by_suffix(cubemx_dir, ".ioc")

    target_ioc = cubemx_dir / f"{workspace_name}.ioc"
    if ioc_file is not None and ioc_file.name.lower() != target_ioc.name.lower():
        ioc_file.rename(target_ioc)
        ioc_file = target_ioc

    if target_ioc.exists():
        lines = read_text(target_ioc).splitlines()
        updated = replace_line_values(
            lines,
            {
                "ProjectManager.ProjectFileName": f"{workspace_name}.ioc",
                "ProjectManager.ProjectName": workspace_name,
            },
        )
        write_text(target_ioc, "\n".join(updated) + "\n")
        return workspace_name, target_ioc

    return workspace_name, ioc_file


def generate_aggregate_header(core_inc: Path) -> None:
    """生成聚合头 cubemx.h，自动包含 Core/Inc 下其它头文件。"""
    agg_header = core_inc / "cubemx.h"
    headers = sorted(
        p.name
        for p in core_inc.glob("*.h")
        if p.is_file() and p.name.lower() != "cubemx.h"
    )

    out: list[str] = [
        "/**",
        "* @file    cubemx.h",
        "* @author  Pickingchip",
        "* @brief   this file is used to include the CubeMX generated peripheral header files.",
        "* @note    Auto-generated by cleanup.py after CubeMX code generation.",
        "* @version 1.0",
        f"* @date    {HEADER_DATE}",
        "*/",
        "",
        "#ifndef __CUBEMX_H",
        "#define __CUBEMX_H",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]

    out.extend(f'#include "{name}"' for name in headers)

    out.extend(
        [
            "",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            "#endif /* __CUBEMX_H */",
            "",
        ]
    )

    write_text(agg_header, "\n".join(out))


def parse_target_toolchain(ioc_file: Optional[Path]) -> Optional[str]:
    """从 .ioc 中解析 ProjectManager.TargetToolchain 的值。"""
    if ioc_file is None or not ioc_file.exists():
        return None
    for line in read_text(ioc_file).splitlines():
        if line.startswith("ProjectManager.TargetToolchain="):
            return line.split("=", 1)[1].strip()
    return None


def update_eide_for_mdk(eide_file: Path) -> None:
    """按 MDK 流程更新 eide.yml：startup 路径切到 arm，toolchain 设为 AC6。"""
    if not eide_file.exists():
        return
    text = read_text(eide_file)
    text = text.replace("Source/gcc/", "Source/arm/")
    text = re.sub(r"^(\s*toolchain:\s*).*$", r"\1AC6", text, flags=re.MULTILINE)
    write_text(eide_file, text)


def update_eide_for_makefile(eide_file: Path, ld_file_name: Optional[str]) -> None:
    """按 Makefile 流程更新 eide.yml：GCC 段 ld 路径、toolchain 与 startup 路径。"""
    if not eide_file.exists():
        return

    lines = read_text(eide_file).splitlines()
    out: list[str] = []
    in_gcc = False
    for line in lines:
        if re.match(r"^\s*GCC:\s*$", line):
            in_gcc = True
            out.append(line)
            continue

        if in_gcc and re.match(r"^\s*scatterFilePath:\s*", line):
            leading = re.match(r"^(\s*)", line).group(1)
            if ld_file_name:
                ld_rel = f".\\CubeMX\\Drivers\\CMSIS\\Device\\ST\\STM32G4xx\\Source\\ld\\{ld_file_name}"
                out.append(f"{leading}scatterFilePath: {ld_rel}")
            else:
                out.append(line)
            in_gcc = False
            continue

        out.append(line)

    text = "\n".join(out) + "\n"
    text = re.sub(r"^(\s*toolchain:\s*).*$", r"\1GCC", text, flags=re.MULTILINE)
    text = text.replace("Source/arm/", "Source/gcc/")
    write_text(eide_file, text)


def cleanup_mdk(cubemx_dir: Path, root_dir: Path) -> None:
    """执行 MDK 分支清理：更新 eide、删除 Makefile、删除 MDK-ARM 目录。"""
    eide_file = root_dir / ".eide" / "eide.yml"
    target_dir = cubemx_dir / "MDK-ARM"
    makefile = cubemx_dir / "Makefile"

    update_eide_for_mdk(eide_file)
    remove_file(makefile)
    remove_dir(target_dir)


def cleanup_makefile(cubemx_dir: Path, root_dir: Path) -> None:
    """执行 Makefile 分支清理：删除构建产物、移动 ld、更新 eide。"""
    eide_file = root_dir / ".eide" / "eide.yml"
    makefile = cubemx_dir / "Makefile"
    ld_target_dir = root_dir / "CubeMX" / "Drivers" / "CMSIS" / "Device" / "ST" / "STM32G4xx" / "Source" / "ld"

    ld_source = find_first_by_suffix(cubemx_dir, ".ld")
    ld_file_name = ld_source.name if ld_source else None

    asm_files = sorted(cubemx_dir.glob("*.s"))

    remove_file(makefile)
    for asm in asm_files:
        remove_file(asm)

    if ld_source:
        ld_target_dir.mkdir(parents=True, exist_ok=True)
        shutil.move(str(ld_source), str(ld_target_dir / ld_source.name))

    update_eide_for_makefile(eide_file, ld_file_name)


def run_cleanup(script_file: Path) -> int:
    """清理主流程：定位目录、同步 ioc、生成头文件、按工具链分支处理。"""
    cubemx_dir = script_file.resolve().parent
    root_dir = cubemx_dir.parent

    workspace_name, ioc_file = update_ioc_file_name(cubemx_dir, root_dir)
    if workspace_name:
        print(f"workspace name: {workspace_name}")
    else:
        print("workspace name: <not found>")

    core_inc = root_dir / "CubeMX" / "Core" / "Inc"
    generate_aggregate_header(core_inc)

    target_toolchain = parse_target_toolchain(ioc_file)
    if not target_toolchain:
        print("target toolchain: <not found>, skip toolchain cleanup")
        return 0

    print(f"target toolchain: {target_toolchain}")
    if target_toolchain.lower() == "makefile":
        cleanup_makefile(cubemx_dir, root_dir)
    else:
        cleanup_mdk(cubemx_dir, root_dir)

    return 0


def main() -> int:
    """命令行入口：解析参数并启动清理流程。"""
    return run_cleanup(Path(__file__))


if __name__ == "__main__":
    raise SystemExit(main())
