/**
* @file    cubemx.h
* @author  Pickingchip
* @brief   this file is used to include the CubeMX generated peripheral header files.
* @note    Auto-generated by cleanup.py after CubeMX code generation.
* @version 1.0
* @date    2026-03-16
*/

#ifndef __CUBEMX_H
#define __CUBEMX_H

#ifdef __cplusplus
extern "C" {
#endif

#include "dma.h"
#include "fdcan.h"
#include "gpio.h"
#include "main.h"
#include "stm32g4xx_hal_conf.h"
#include "stm32g4xx_it.h"
#include "usart.h"

#ifdef __cplusplus
}
#endif

#endif /* __CUBEMX_H */
